language: node_js
node_js:
  - "8"
cache:
  directories:
  - node_modules #Cache node_modules for faster builds
script:
  - npm test --coverage #Runs Tests
  - npm run build #Creats a production build
after_script: # Upload coverage reports 
  - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN npm run coveralls
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local_dir: build
  on:
    branch: master